# Generated by Django 6.0.2 on 2026-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ram_gb', models.PositiveIntegerField(verbose_name='RAM (GB)')),
                ('storage_gb', models.PositiveIntegerField(verbose_name='Almacenamiento (GB)')),
                ('processor', models.CharField(max_length=150, verbose_name='Procesador')),
                ('battery_mah', models.PositiveIntegerField(verbose_name='Batería (mAh)')),
                ('camera_mp', models.PositiveIntegerField(verbose_name='Cámara (MP)')),
                ('screen_inches', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pantalla (pulgadas)')),
                ('os', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('other', 'Otro')], max_length=20, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
    ]
