# Generated by Django 6.0.2 on 2026-03-02 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item de orden', 'verbose_name_plural': 'Items de orden'},
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Precio unitario')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Total')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Tarjeta de Credito'), ('debit_card', 'Tarjeta Debito'), ('pse', 'PSE'), ('nequi', 'Nequi'), ('davivienda', 'Davivienda')], default='credit_card', max_length=20, verbose_name='Metodo de pago')),
                ('status', models.CharField(choices=[('approved', 'Aprobado'), ('pending', 'Pendiente'), ('rejected', 'Rechazado')], default='pending', editable=False, max_length=20, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='ID Transaccion')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
