# Generated by Django 6.0.1 on 2026-02-10 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='camara',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='bateria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='procesador',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ram',
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('PAGADA', 'Pagada')], default='CREADA', max_length=10),
        ),
        migrations.AlterField(
            model_name='orden',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
