# Generated by Django 6.0.1 on 2026-02-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_camara_producto_nombre_remove_orden_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
