# Generated by Django 6.0.2 on 2026-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(max_length=100, verbose_name='Departamento')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='Barrio')),
                ('street', models.CharField(max_length=200, verbose_name='Dirección')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Referencia')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
